### PR TITLE
Add options to change stream and file log level

### PR DESCRIPTION
**Pull request by dd-jy**
Change file log level to INFO

## Description
(Please describe what this PR do.)
The log file needs to be written more detail information. So please change the file log level to lower level (INFO).

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @dd-jy ,

fosslight_util supports python 3.6+ and
pathlib is known to be included in the built-in module since Python 3.4.

Should it still be included in the requirements.txt?

**Comment by dd-jy** [comment]
It's my mistake. I tested python2.x.
I removed the last commit.

**Comment by soimkim** [comment]
Dear @dd-jy ,

If you want to distribute this to pypi, also upload the commit to upgrade version in setup.py.
And if you release after merge, it is also distributed to pypi.

**Comment by soimkim** [comment]
@dd-jy , LGTM. :-)

**Pull request merged**
