### PR TITLE
Add exception for checking version

### PR DESCRIPTION
**Pull request by soimkim**
## Description
Add exception for checking version.
- If the Internet does not work, add an exception to the version check failure in Pypi when calling init_log.

## Type of change
Please insert 'x' one of the type of change.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
@bjk7119 , Please review this PR.

**Review by bjk7119 — APPROVED** [review]
LGTM :)

**Comment by soimkim** [comment]
Do not merge yet.

**Comment by soimkim** [comment]
@bjk7119 , Please re-review this PR. I added one more exception.

**Review by bjk7119 — APPROVED** [review]
LGTM :)

**Pull request merged**
