### PR TITLE
Modify Color log code using coloredlogs

### PR DESCRIPTION
**Pull request by bjk7119**
## Description
Modify Color log code using coloredlogs

## Type of change
Please insert 'x' one of the type of change.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by soimkim** [comment]
Dear @bjk7119 ,
Would you attach an example of the log output to the screen?

**Comment by bjk7119** [comment]
Dear @soimkim 
If you use older version of any FL package, you can see the below comment.
image

And if you use the latest version, the comment will not be appeared.

**Comment by soimkim** [comment]
Dear @bjk7119 ,
It looks great. Let's merge it.

**Comment by bjk7119** [comment]
@soimkim 
I think I have an eraser in my brain. I won't forget it from now on. 
Thx.

**Pull request merged**
