### PR TITLE
Add GitHub Actions Workflow for Testing

### PR DESCRIPTION
**Pull request by JaeHyuckSa**
## Description

This PR introduces a Continuous Integration (CI) workflow that runs automated tests and checks code coverage across multiple Python versions (3.8 through 3.12). The workflow is triggered on push events to the main branch, on pull requests, and when a release is published. It also includes a workflow_dispatch trigger for manual execution. The workflow uses a matrix strategy to test the code across different Python versions and shards, ensuring broad compatibility and efficient parallel testing.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues
- https://github.com/fosslight/fosslight_util/issues/181

### CODE REVIEW

**Comment by saJaeHyukc** [comment]
If you would like to add code coverage using Codecov as mentioned in the issue, I can include it in the workflow. However, please note that you will need to set the Codecov token in the repository secrets to enable this integration.

**Comment by soimkim** [comment]
Test 팀에서 진행하는 PR인가요? 'ㅅ ' ) ???

**Comment by saJaeHyukc** [comment]
> Test 팀에서 진행하는 PR인가요? 'ㅅ ' ) ??? [https://github.com/fosslight/fosslight_util/blob/main/.github/workflows/pull-request.yml에서](https://github.com/fosslight/fosslight_util/blob/main/.github/workflows/pull-request.yml%EC%97%90%EC%84%9C) python 버전 추가하는 것과 동일해보입니다.

넵 테스트 팀에서 진행하는 것입니다

**Comment by saJaeHyukc** [comment]
> Test 팀에서 진행하는 PR인가요? 'ㅅ ' ) ??? [https://github.com/fosslight/fosslight_util/blob/main/.github/workflows/pull-request.yml에서](https://github.com/fosslight/fosslight_util/blob/main/.github/workflows/pull-request.yml%EC%97%90%EC%84%9C) python 버전 추가하는 것과 동일해보입니다.

해당 부분 수정하도록 하겠습니다 :)

**Comment by soimkim** [comment]
https://github.com/fosslight/fosslight_util/pull/189 반영되어 본 이슈는 close합니다.

**Pull request closed without merging**
